#!/usr/bin/env python3
"""
Simple visualization script for result.csv generated by test_erg
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

def plot_csv(csv_path="result.csv"):
    """Plot signals from CSV file."""

    if not Path(csv_path).exists():
        print(f"Error: {csv_path} not found")
        print("Run test_erg first to generate the CSV file")
        return

    # Read CSV
    df = pd.read_csv(csv_path)

    print(f"Loaded {len(df)} samples from {csv_path}")
    print(f"Columns: {', '.join(df.columns)}")

    # Calculate frequency from Time signal
    if 'Time' in df.columns and len(df) >= 2:
        dt = df['Time'].iloc[1] - df['Time'].iloc[0]
        freq = 1.0 / dt
        print(f"Sampling frequency: {freq:.3f} Hz (dt = {dt:.6f} s)")
        print(f"Time range: {df['Time'].iloc[0]:.3f} to {df['Time'].iloc[-1]:.3f} seconds")

    # Create subplots
    fig, axes = plt.subplots(3, 1, figsize=(12, 8), sharex=True)
    fig.suptitle('CarMaker Simulation Results', fontsize=14, fontweight='bold')

    # Plot Car.ax (acceleration)
    if 'Car.ax' in df.columns:
        axes[0].plot(df['Time'], df['Car.ax'], 'b-', linewidth=1)
        axes[0].set_ylabel('Car.ax [m/s²]')
        axes[0].grid(True, alpha=0.3)
        axes[0].set_title('Longitudinal Acceleration')

    # Plot Car.v (velocity)
    if 'Car.v' in df.columns:
        axes[1].plot(df['Time'], df['Car.v'], 'g-', linewidth=1)
        axes[1].set_ylabel('Car.v [m/s]')
        axes[1].grid(True, alpha=0.3)
        axes[1].set_title('Vehicle Velocity')


    axes[2].set_xlabel('Time [s]')

    plt.tight_layout()

    # Save plot
    output_path = Path(csv_path).with_suffix('.png')
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"\nPlot saved to: {output_path}")

    # Show plot
    plt.show()

if __name__ == "__main__":
    import sys

    csv_path = sys.argv[1] if len(sys.argv) > 1 else "result_avx2.csv"
    plot_csv(csv_path)
